name: example
environment:
  sdk: ">=3.8.0 <4.0.0"

publish_to: none

dependencies:
  json_annotation: 4.9.0
  coollocalizations:
    path: ../

dev_dependencies:
  coolint: 2.0.0
  build_runner: any
  json_serializable: ^6.9.5
