name: coollocalizations_generator
environment:
  sdk: ">=3.2.4 <4.0.0"
publish_to: none

dependencies:
  args: ^2.4.2
  path: ^1.9.0
  dart_style: ^3.1.3
  intl: any

dev_dependencies:
  coolint: 2.0.0
  build_runner: any
